### ISSUE TITLE
beacon can not be placed in some ways that should be possible

### ISSUE THREAD

**Issue by SwissalpS** [OgelGames/beacon#1]
- using deployer does not work
- using replacer orientation is incorrect
- can't place without beam
Edit: why can't screwdriver be used? Is there a reason for not using param2 for orientation?

**Comment by OgelGames** [comment]
> * using deployer does not work

Strange, it worked when I tested it...

> * using replacer orientation is incorrect

I believe that is because of the replacer not passing a correct `pointed_thing` to the `on_place` function.

> * can't place without beam

That's by design, the beam is what gives the beacon it's power, so to speak. 

>   Edit: why can't screwdriver be used? Is there a reason for not using param2 for orientation?

I assume you mean to use param2 when placing the beacon, because the beam does use param2 for orientation. 

I originally chose not to use param2 for placement just because it seemed to make placing the beacon more difficult, but I'll have a look into it again, and see if I can make it work, because that should also fix the replacer issue. 


Edit: What do you think about having the beam only be added after the beacon has been activated? That would also solve the potential lag issue when placing a lot of beacons.

**Comment by OgelGames** [comment]
Hopefully everything works now... 😄

**Comment by SwissalpS** [comment]
> * using deployer does not work

after further testing I found out that beam will point in direction deployer has opening.
Also needs 3 nodes space or refuses to be placed. That's a pity as the box itself is now the one giving the enhancements. Also just the box is also a good light.



> believe that is because of the replacer not passing a correct `pointed_thing` to the `on_place`

possible, but don't think so. It's more likely to be the param2 issue. BTW field mode only placed one beacon.



> What do you think about having the beam only be added after the beacon has been activated?

Now that the magic is in box-node, I don't see why there needs to be a beacon to give powers.
Not having a beam without enhancements would be a pity. Most useful part of being able to place beacons close together is the cool light.
Maybe a separate toggle for the beam independent from the enhancement activation.

I have noticed beams vanishing, that's dangerous as one of my space-ships uses these as walls.

Was not able to build onto box, not even with sneak-click, but replacer worked.

P.S. these test-reports based on currently active version on pandorabox.

**Comment by SwissalpS** [comment]
Constructor can only take/place vertical beams that point upward. I suspect this is also related to param2 (digtron would have the same trouble)

**Comment by OgelGames** [comment]
> P.S. these test-reports based on currently active version on pandorabox.

Please test the new version, some of these should be fixed now.

Clearly there wasn't enough testing done before launching it on the server... At least it hasn't caused any crashes as far as I know...

**Comment by SwissalpS** [comment]
> Clearly there wasn't enough testing done before

I think there was enough testing done, these issues only show in production. This is not banking software :D
Sure some could have been found...
