### ISSUE TITLE
beams without boxes are still evaporating

### ISSUE THREAD

**Issue by SwissalpS** [OgelGames/beacon#8]
It doesn't take long, if there is no supporting box, they tend to vanish no matter which orientation.

**Comment by OgelGames** [comment]
By design beacon beams are supposed to not exist without a beacon, but they also shouldn't disappear if they have a node below them (relative to the orientation).

Here is the code that controls the cleanup of floating beams:
https://github.com/OgelGames/beacon/blob/801cac9da19460fe0a57a27f81d387f7eb2481a3/register.lua#L125-L137

**Comment by SwissalpS** [comment]
> (relative to the orientation).

That must have been my mistake. I repeated the test paying better attention and they seem to stay now :)
Sorry.
